### ISSUE TITLE
Cannot add programs with parameters

### ISSUE THREAD

**Issue by crazy-max** [jalvarez54/Ja.LessUACRunner#2]
Would be nice to add arguments dynamically from Pg.Command.exe like :

`Pg.Command.exe myprogramshortcut arg1 arg2 arg3`

**Comment by jalvarez54** [comment]
[10076-001] CHANGE: Changes to the processing of command line arguments
        Made for -configa option.
        New arguments: -configa [shortcut] "path/filename" ["filename arguments"]
        so we have 2, 3 or 4 command types.
            2args    -configa "path/filename"
            3args    -configa shortcut "path/filename"
            3args    -configa "path/filename" "filename arguments"
            4args    -configa shortcut "path/filename" "filename arguments"
        We will store to keys:
            one for "path/filename" ==> appToRun.shortcut or appToRun.filename (prefix appToRun) 
            one for "filename arguments" ==> appToRun.filename.args (prefix appToRun + sufix args) 
        Affected: ChoiceConfigAdd, ChoiceConfigDelete, ChoiceHelp, ChoiceRunTheProcess
        Work fine with notepad passing path/filename.txt, firefox passing www.mozilla.org,
        not with WinWord, nor vs2015 and PsExec this last one must run from a console.
    [10076-002] ADD: Some settings in app.config
    [10076-003] CHANGE: Ja.LessUACRunner.Command.GetInstaller
        Using _servicePath initialyzed from settings.
        So we dont have to add reference to service.
    [10076-004] ADD: command = shortcut + "application to run parameters"
