### ISSUE TITLE
Implement a more efficient configuration

### ISSUE THREAD

**Issue by crazy-max** [jalvarez54/Ja.LessUACRunner#5]
Instead of the basic `App.config` can you implement a more efficient configuration ?

## Solution 1 : Dictionarysectionhandler (XML file)

More info : https://weblog.west-wind.com/posts/2012/Dec/28/Building-a-better-NET-Application-Configuration-Class-revisited

I thought of a structure like this for Pg.Command :

```xml
<configuration>
  <configSections>
    <section name="general">
      <add key="PipeConnectTimeOut" value="10000" />
    </section>
    <sectionGroup name="allowedApps">
      <section name="app1" type="System.Configuration.NameValueSectionHandler" />
      <section name="app2" type="System.Configuration.NameValueSectionHandler" />
    </sectionGroup>
  </configSections>
  <allowedApps>
    <app1>
      <add key="name" value="app1" />
      <add key="path" value="C:\MyApp1\app1.exe" />
      <add key="arg1" value="-anarg" />
      <add key="arg2" value="-anotherarg" />
    </app1>
    <app2>
      <add key="name" value="app2" />
      <add key="path" value="C:\MyApp2\app2.exe" />
    </app2>
  </allowedApps>
</configuration>
```

## Solution 2 : INI file

This one is popular on Nuget : https://www.nuget.org/packages/MadMilkman.Ini

I think of a structure like this for Pg.Command :

```ini
[general]
PipeConnectTimeOut = 10000

[app-regedit]
name = "regedit"
path = "C:\Windows\SysWOW64\regedit.exe"
args = ""

[app-number2]
name = "number2"
path = "C:\MyAppNumber2\number2.exe"
args = "arg1 arg2 arg3"

etc...
```

**Comment by jalvarez54** [comment]
The Ja.LessUACRunner.Command project appSettings section is used to map a shortcut to a path/filename.
    If later this section should also be used to store other settings, this would cause problems.
    We could develop a custom section for this mapping, but it worth the hassle.
    So instead we adopt the following naming convention for key(shortcut)/value (path / filename) pairs.
    The shortcut will be stored in the form appToRun.shortcut_name. No changes for the user who will handle always
    that shortcut_name.
    In other word, this change is transparent for the user.

**Comment by jalvarez54** [comment]
Done v4.0.0.0
